// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsN3hMP-CTMXRQ9bqnG63JKpKU1Hl__BY',
    appId: '1:867327943539:web:75d012af7a7131037d1b06',
    messagingSenderId: '867327943539',
    projectId: 'eco-54d2b',
    authDomain: 'eco-54d2b.firebaseapp.com',
    storageBucket: 'eco-54d2b.firebasestorage.app',
    measurementId: 'G-Y2MXPVFENN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Z5iw5WZHcXYGv7WfE84tUADBGEN7R8Y',
    appId: '1:867327943539:android:79fa68575d4e0f6b7d1b06',
    messagingSenderId: '867327943539',
    projectId: 'eco-54d2b',
    storageBucket: 'eco-54d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClQS0PmkhXw4017WxnENIGxbE4MHDtgkI',
    appId: '1:867327943539:ios:e9f1d1eebb3afe9f7d1b06',
    messagingSenderId: '867327943539',
    projectId: 'eco-54d2b',
    storageBucket: 'eco-54d2b.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClQS0PmkhXw4017WxnENIGxbE4MHDtgkI',
    appId: '1:867327943539:ios:e9f1d1eebb3afe9f7d1b06',
    messagingSenderId: '867327943539',
    projectId: 'eco-54d2b',
    storageBucket: 'eco-54d2b.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsN3hMP-CTMXRQ9bqnG63JKpKU1Hl__BY',
    appId: '1:867327943539:web:7cfdf934b3ba6dc57d1b06',
    messagingSenderId: '867327943539',
    projectId: 'eco-54d2b',
    authDomain: 'eco-54d2b.firebaseapp.com',
    storageBucket: 'eco-54d2b.firebasestorage.app',
    measurementId: 'G-2LMDTKVH6L',
  );

}